(function () {
  "use strict";

  function parsePattern(text) {
    return text.trim().split("\n").map((line) => line.trim());
  }

  function artPreset({ id, nameJa, width, height, category, pattern }) {
    return {
      id,
      nameJa,
      name: nameJa,
      width,
      height,
      category,
      pattern: parsePattern(pattern)
    };
  }

  const LICENSED_BLOOD_GOAL_PRESETS = [];

  const ART_BLOOD_GOAL_PRESETS = [
    artPreset({
      id: "sculpted-eye",
      nameJa: "彫刻の目",
      width: 40,
      height: 24,
      category: "sculpture",
      pattern: `
        ........................................
        ........................................
        ............SSSSSSSSSSSSSS.............
        .........SSSSMMMMMMMMMMMMSSSS..........
        .......SSSMMMMMMMMMMMMMMMMMMSSS........
        .....SSSMMMMMOOOOOOOOOOMMMMMMSSS.......
        ....SSMMMMOOOHHHHHHHHHHOOOMMMMSS.......
        ...SSMMMOOHHHHAAAAAAHHHHOOOMMMSS.......
        ..SSMMMOOHHHAAAAAAAAAAHHHOOOMMMSS......
        ..SSMMOOHHAAAMMMMMMMMAAHHOOOMMSS......
        .SSMMOOHHAAAMMSSSSSSMMAAHHOOOMMS......
        .SSMMOOHHAAAMSSSSSSSSMAAHHOOOMMS......
        .SSMMOOHHAAAMSSSSSSSSMAAHHOOOMMS......
        ..SSMMOOHHAAAMMSSSSSSMMAAHHOOOMMS.....
        ..SSMMMOOHHAAAMMMMMMMMAAHHOOOMMSS.....
        ...SSMMMOOHHHAAAAAAAAHHHOOOMMMSS......
        ....SSMMMMOOOHHHHHHHHOOOMMMMSS........
        .....SSSMMMMMOOOOOOOOOMMMMMSSS.........
        .......SSSMMMMMMMMMMMMMMSSS............
        .........SSSSMMMMMMMMSSSS..............
        .............SSSSSSSS...................
        ........................................
        ........................................
        ........................................
      `
    }),
    artPreset({
      id: "stone-hand",
      nameJa: "石の手",
      width: 32,
      height: 40,
      category: "sculpture",
      pattern: `
        ................................
        ............SSSS................
        ...........SMMMMS...............
        ..........SMMAMMS...............
        ..........SMMMMMS...............
        .......SS.SMMMMS..SS............
        ......SMMSSMMMMS.SMMSS..........
        ......SMMMMMMMMSSMMMMS..........
        ......SMMAMMMMMMMMMMMS..........
        ......SMMMMMMMMMMMMMMS..........
        ......SMMMMMMMMMMMMMMS..........
        .......SMMMMMMMMMMMMMS..........
        .......SMMMMMMMMMMMMMS..........
        ........SMMMMMMMMMMMMSS.........
        ........SMMMMMMMMMMMMMSS........
        .........SMMMMMMMMMMMMMS........
        .........SMMMMMMMMMMMMMS........
        ..........SMMMMMMMMMMMMS........
        ..........SMMMMMMMMMMMMSS.......
        ...........SMMMMMMMMMMMMSS......
        ...........SMMMMMMMMMMMMMS......
        ............SMMMMMMMMMMMMS......
        ............SMMMMMMMMMMMMS......
        .............SMMMMMMMMMMSS......
        .............SMMMMMMMMMSS.......
        ..............SMMMMMMMSS........
        ..............SMMMMMMSS.........
        ..............SMMMMMS...........
        .............SMMMMMMS...........
        ............SMMMMMMSS...........
        ...........SMMMMMMSS............
        ..........SMMMMMMSS.............
        .........SMMMMMMSS..............
        ........SMMMMMMSS...............
        .......SMMMMMSS.................
        ......SMMMMSS...................
        ......SSSS......................
        ................................
        ................................
        ................................
      `
    }),
    artPreset({
      id: "skull-relief",
      nameJa: "髑髏",
      width: 37,
      height: 36,
      category: "memento",
      pattern: `
        ....................................
        ............SSSSSSSSSS..............
        .........SSSMMMMMMMMMMSSS...........
        .......SSMMMMMMMMMMMMMMMMSS.........
        ......SMMMMMMMMMMMMMMMMMMMMSS.......
        .....SMMMMMAAAMMMMMMAAAMMMMMS.......
        ....SMMMMMAAAAAMMMMAAAAAMMMMMSS.....
        ...SMMMMMMSSSSMMMMSSSSMMMMMMMMS.....
        ...SMMMMMSSSSSSMMSSSSSSMMMMMMMS.....
        ..SMMMMMMSSSSSSMMSSSSSSMMMMMMMMS....
        ..SMMMMMMMSSSSMMMMSSSSMMMMMMMMMS....
        ..SMMMMMMMMMMMMMMMMMMMMMMMMMMMMMS....
        ..SMMMMMMMMMMMMSSMMMMMMMMMMMMMMMS....
        ...SMMMMMMMMMMSSSSMMMMMMMMMMMMMS.....
        ...SMMMMMMMMMSSSSSSMMMMMMMMMMMMS.....
        ....SMMMMMMMMSSSSSSMMMMMMMMMMMS......
        .....SMMMMMMMMSSSSMMMMMMMMMMMSS......
        ......SMMMMMMMMMMMMMMMMMMMMMSS.......
        .......SMMMSSMMMMMMMMSSMMMSS........
        ........SMMSSSSSSSSSSSSMMSS.........
        ........SMMMAAMMAAMMAAMMMS..........
        ........SMMMAAMMAAMMAAMMMS..........
        .........SMMMMMMMMMMMMMS.............
        .........SMMSSSSSSSSMMMS.............
        ..........SSMMMMMMMMSS...............
        ............SSSSSSSS.................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
      `
    }),
    artPreset({
      id: "profile-shadow",
      nameJa: "横顔",
      width: 32,
      height: 40,
      category: "portrait",
      pattern: `
        ................................
        ............SSSSSS..............
        ..........SSMMMMMMSS............
        ........SSMMMMMMMMMMSS..........
        .......SMMMMMMMMMMMMMS..........
        ......SMMMMMMMMMMMMMMMS.........
        .....SMMMMMMMMMMMMMMMMS.........
        .....SMMMMMMMMMMAAMMMMS.........
        ....SMMMMMMMMMMMAAMMMMSS........
        ....SMMMMMMMMMMMMMMMMMMS........
        ....SMMMMMMMMMMMMMMMMMMS........
        ....SMMMMMMMMMMMMMMMMMMS........
        ....SMMMMMMMMMMMMMMMMSS.........
        .....SMMMMMMMMMMMMMMSS..........
        ......SMMMMMMMMMMMMMS...........
        .......SMMMMMMMMMMMMSS..........
        ........SMMMMMMMMMMMMSS.........
        .........SMMMMMMMMMMMMS.........
        ..........SSMMMMMMMMMMMS........
        ............SMMMMMMMMMMS........
        .............SMMMMMMMMMSS.......
        .............SMMMMMMMMMMS.......
        ............SMMMMMMMMMMMS.......
        ...........SMMMMMMMMMMMMMS......
        ..........SMMMMMMMMMMMMMMSS.....
        .........SMMMMMMMMMMMMMMMMSS....
        ........SMMMMMMMMMMMMMMMMMMSS...
        .......SMMMMMMMMMMMMMMMMMMMMSS..
        ......SMMMMMMMMMMMMMMMMMMMMMMS..
        .....SSSSSSSSSSSSSSSSSSSSSSSSS.
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
      `
    }),
    artPreset({
      id: "moon-city",
      nameJa: "月夜の街",
      width: 56,
      height: 32,
      category: "landscape",
      pattern: `
        ........................................................
        ........................................AAAA............
        ......................................AAMMMMAA..........
        .....................................AMMMMMMMA..........
        .....................................AMMMMMMMA..........
        ......................................AAMMMMAA..........
        ........................................AAAA............
        ........................................................
        ..............MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..........
        ............MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM........
        ..........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......
        ........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM....
        ......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....
        ......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....
        ......SSSS..AA..SSSS....AA..SSSS..AA..SSSS....AA......
        ......SSSS......SSSS........SSSS......SSSS.............
        ......SSSS..AA..SSSS..AA....SSSS..AA..SSSS..AA........
        ......SSSS......SSSS........SSSS......SSSS.............
        ....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....
        ....SSSS..AA..SSSS....AA..SSSS..AA..SSSS....AA..SS....
        ....SSSS......SSSS........SSSS......SSSS........SSS....
        ..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..
        ..SSSS..AA..SSSS..AA..SSSS....AA..SSSS..AA..SSSSSSSS..
        ..SSSS......SSSS......SSSS........SSSS......SSSSSSSS...
        SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
        SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
      `
    }),
    artPreset({
      id: "cloud-mountain",
      nameJa: "雲海の山",
      width: 56,
      height: 34,
      category: "landscape",
      pattern: `
        ........................................................
        ............................AA..........................
        ...........................AMMA.........................
        ..........................AMMMMA........................
        .........................AMMMMMMA.......................
        ........................AMMSSMMMMA......................
        .......................AMMSSSSMMMMA.....................
        ......................AMMSSSSSSMMMMA....................
        .....................AMMSSSSSSSSMMMM....................
        ....................AMMSSSMMMMSSSMMMMA..................
        ...................AMMSSMMMMMMMMSSMMMMA.................
        ..................AMMSSMMMMMMMMMMSSMMMMA................
        .................AMMSSMMMMMMMMMMMMSSMMMMA...............
        ................AMMSSMMMMMMMMMMMMMMSSMMMMA..............
        ...............AMMSSMMMMMMMMMMMMMMMMSSMMMMA.............
        ..............AMMSSMMMMMMMMMMMMMMMMMMSSMMMMA............
        .............AMMSSMMMMMMMMMMMMMMMMMMMMSSMMMM............
        ............AMMSSMMMMMMMMMMMMMMMMMMMMMMSSMMMMA..........
        ...........AMMSSMMMMMMMMMMMMMMMMMMMMMMMMSSMMMMA.........
        ..........AMMSSMMMMMMMMMMMMMMMMMMMMMMMMMMSSMMMMA........
        .........AMMSSMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSMMMM........
        ........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........
        .....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.....
        ...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...
        .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.
        MMMMMMMM....MMMMMMMM....MMMMMMMM....MMMMMMMM....MMMMMMMM
        ...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...
        .....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.....
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
      `
    }),
    artPreset({
      id: "forest-light",
      nameJa: "木漏れ日の森",
      width: 56,
      height: 38,
      category: "landscape",
      pattern: `
        ..........A.................A.................A.........
        .........AM...............AMM...............AM..........
        ........AMM..............AMM...............AMM..........
        .......AMM..............AMM...............AMM...........
        ......AMM..............AMM...............AMM............
        .....AMM..............AMM...............AMM.............
        SSS..MM..SSSSSSS..SS..MM..SSSSSSS..SS..MM..SSSSSSS....
        SSS..MM..SSSSSSS..SS..MM..SSSSSSS..SS..MM..SSSSSSS....
        SSS..MM..SSSSSSS..SS..MM..SSSSSSS..SS..MM..SSSSSSS....
        SSS..MM..SSSSSSS..SS..MM..SSSSSSS..SS..MM..SSSSSSS....
        SSS..MM..SSSSSSS..SS..MM..SSSSSSS..SS..MM..SSSSSSS....
        SSS..MM..SSSSSSS..SS..MM..SSSSSSS..SS..MM..SSSSSSS....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..MMMMMMM..SS..MM..MMMMMMM..SS..MM..MMMMMMM....
        SSS..MM..SSSSSSS..SS..MM..SSSSSSS..SS..MM..SSSSSSS....
        SSS..MM..SSSSSSS..SS..MM..SSSSSSS..SS..MM..SSSSSSS....
        SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
        SSSSMMMMMMMMSSSSMMMMMMMMSSSSMMMMMMMMSSSSMMMMMMMMSSSS
        SSSSMMMMMMMMSSSSMMMMMMMMSSSSMMMMMMMMSSSSMMMMMMMMSSSS
        ..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..
        ....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM....
        ......MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
        ........................................................
      `
    }),
    artPreset({
      id: "glass-drop",
      nameJa: "玻璃の水滴",
      width: 36,
      height: 40,
      category: "object",
      pattern: `
        ....................................
        ................AA..................
        ...............AMMA.................
        ..............AMMMMA................
        .............AMMMMMMA...............
        ............AMMMMMMMMA..............
        ...........AMMMMMMMMMMA.............
        ..........AMMMMMMMMMMMMA............
        .........AMMMMMMMMMMMMMMA...........
        ........AMMMMMMMMMMMMMMMMA..........
        .......AMMMMMMMMMMMMMMMMMMA.........
        ......AMMMMMAAAAMMMMMMMMMMMA........
        .....AMMMMMMAAAMMMMMMMMMMMMMA.......
        ....AMMMMMMMMMMMMMMMMMMMMMMMMA......
        ...AMMMMMMMMMMMMMMMMMMMMMMMMMMA.....
        ..AMMMMMMMMMMMMMMMMMMMMMMMMMMMMA....
        .AMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMA...
        .AMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMA...
        AMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMA..
        AMMMMMMMMMMMMMMSSSSSSMMMMMMMMMMMMA..
        AMMMMMMMMMMMMSSSSSSSSSSMMMMMMMMMMA..
        AMMMMMMMMMMMSSSSSSSSSSSSMMMMMMMMMA..
        AMMMMMMMMMMMSSSSSSSSSSSSMMMMMMMMMA..
        .AMMMMMMMMMMMSSSSSSSSSSMMMMMMMMMA...
        .AMMMMMMMMMMMMMSSSSSSMMMMMMMMMMMA...
        ..AMMMMMMMMMMMMMMMMMMMMMMMMMMMMA....
        ...AMMMMMMMMMMMMMMMMMMMMMMMMMMA.....
        ....AMMMMMMMMMMMMMMMMMMMMMMMMA......
        .....AMMMMMMMMMMMMMMMMMMMMMMA.......
        ......AMMMMMMMMMMMMMMMMMMMMA........
        .......AMMMMMMMMMMMMMMMMMA..........
        ........AMMMMMMMMMMMMMMMA...........
        .........AMMMMMMMMMMMMA.............
        ..........AMMMMMMMMMA...............
        ...........SSSSSSSS.................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
      `
    }),
    artPreset({
      id: "old-key",
      nameJa: "古鍵",
      width: 28,
      height: 52,
      category: "object",
      pattern: `
        ............................
        ..........SSSSSSSS..........
        ........SSMMMMMMSS..........
        .......SMMMMAAAAMSS.........
        ......SMMMSSSSSMMMS.........
        ......SMMSS...SSMMS.........
        .....SMMSS.....SSMMS........
        .....SMMSS.....SSMMS........
        .....SMMMSS...SSMMMS........
        ......SMMMSSSSSMMMS.........
        .......SMMMMMMMMMS..........
        ........SSMMMMSSS...........
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMSSSS..........
        ..........SMMMMMMSS.........
        ..........SMMMSSSS..........
        ..........SMMMS.............
        ..........SMMMS.............
        ..........SMMMSSSSS.........
        ..........SMMMMMMMSS........
        ..........SMMMSSSSS.........
        ..........SMMMS.............
        ..........SSSSS.............
        ............................
        ............................
        ............................
        ............................
        ............................
        ............................
        ............................
      `
    }),
    artPreset({
      id: "old-coin",
      nameJa: "古銭",
      width: 36,
      height: 36,
      category: "object",
      pattern: `
        ....................................
        ............SSSSSSSSSS..............
        .........SSSMMMMMMMMMMSSS...........
        .......SSMMMMMMMMMMMMMMMMSS.........
        .....SSMMMMMMMMMMMMMMMMMMMMSS.......
        ....SMMMMMMMMMMMMMMMMMMMMMMMMS......
        ...SMMMMMMAAAAAAAAAAAAMMMMMMMMS.....
        ..SMMMMMAASSSSSSSSSSSSAAMMMMMMS....
        ..SMMMMAASMMMMMMMMMMMMSAAMMMMMS....
        .SMMMMMASMMMMMMMMMMMMMMMSAMMMMMS...
        .SMMMMMASMMMMSSSSMMMMMMMSAMMMMMS...
        SMMMMMMASMMMSSSSSSMMMMMMSAMMMMMMS..
        SMMMMMMASMMMSSSSSSMMMMMMSAMMMMMMS..
        SMMMMMMASMMMMSSSSMMMMMMMSAMMMMMMS..
        SMMMMMMASMMMMMMMMMMMMMMMSAMMMMMMS..
        SMMMMMMASMMMMMMAAMMMMMMMSAMMMMMMS..
        SMMMMMMASMMMMMAAAAMMMMMMSAMMMMMMS..
        SMMMMMMASMMMMMMAAMMMMMMMSAMMMMMMS..
        SMMMMMMASMMMMMMMMMMMMMMMSAMMMMMMS..
        SMMMMMMASMMMMMMMMMMMMMMMSAMMMMMMS..
        SMMMMMMMASMMMMMMMMMMMMMSAMMMMMMS...
        .SMMMMMMASSSSSSSSSSSSSSAMMMMMMS....
        .SMMMMMMMAAAAAAAAAAAAAAMMMMMMMS....
        ..SMMMMMMMMMMMMMMMMMMMMMMMMMMS.....
        ...SMMMMMMMMMMMMMMMMMMMMMMMMS......
        ....SMMMMMMMMMMMMMMMMMMMMMMS.......
        .....SSMMMMMMMMMMMMMMMMMMSS........
        .......SSMMMMMMMMMMMMMMSS..........
        .........SSSMMMMMMMMSSS............
        ............SSSSSSSS...............
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
      `
    }),
    artPreset({
      id: "candle-light",
      nameJa: "灯る蝋燭",
      width: 32,
      height: 52,
      category: "object",
      pattern: `
        ................................
        ...............AA...............
        ..............AMMA..............
        .............AMMMMA.............
        ............AMMMMMMA............
        ...........AMMSSMMMMA...........
        ...........AMMSSMMMMA...........
        ............AMMMMMMA............
        .............AMMMMA.............
        ..............AMMA..............
        ...............SS...............
        ...............SS...............
        ............SSMMMMSS............
        ...........SMMMMMMMS............
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMAAMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMSSMMMS...........
        ..........SMMMSSSMMMS...........
        ..........SMMMMSSMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ..........SMMMMMMMMMS...........
        ...........SMMMMMMMS............
        ............SSMMMMSS............
        .............SSSSSS.............
        ..........SSSSSSSSSSSS..........
        ........SSSSMMMMMMSSSSSS........
        ......SSSSMMMMMMMMMMSSSS........
        .....SSSSMMMMMMMMMMMMSSSS.......
        .....SSSSSSSSSSSSSSSSSSSS.......
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
      `
    }),
    artPreset({
      id: "old-lantern",
      nameJa: "古灯",
      width: 34,
      height: 52,
      category: "object",
      pattern: `
        ..................................
        ..............SSSSSS..............
        ............SSMMMMMMSS............
        ...........SMMMMMMMMMMS...........
        ...........SMMSSSSSSMMS...........
        ............SS......SS............
        ..............SSSSSS..............
        ............SSMMMMMMSS............
        ..........SSMMMMMMMMMMSS..........
        .........SMMMMMMMMMMMMMMS.........
        ........SMMMSSSSSSSSSSMMMS........
        .......SMMSSMMMMMMMMMMSSMMS.......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMAAAAAAAAMSSMS......
        ......SMMSSMMMAAAAAAAAAMSSMS......
        ......SMMSSMMMAAAAAAAAAMSSMS......
        ......SMMSSMMMMAAAAAAAAMSSMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        ......SMMSSMMMMMMMMMMMMSSMMS......
        .......SMMSSMMMMMMMMMMSSMMS.......
        ........SMMMSSSSSSSSSSMMMS........
        .........SMMMMMMMMMMMMMMS.........
        ..........SSMMMMMMMMMMSS..........
        ............SSMMMMMMSS............
        ..............SSSSSS..............
        .............SMMMMMMS.............
        ............SMMMMMMMMS............
        ...........SMMMMMMMMMMS...........
        ..........SMMMMMMMMMMMMS..........
        .........SSSSSSSSSSSSSSS..........
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
      `
    })
  ];

  window.BLOOD_GOAL_PRESETS = [
    ...LICENSED_BLOOD_GOAL_PRESETS,
    ...ART_BLOOD_GOAL_PRESETS
  ];
}());
